### PR TITLE
Start/stop jobs in parallel

### PR DESCRIPTION
**Pull request by tomaszdurka**
For better deployment performance.
Either in Ruby or on Shell (gnu parallel).

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by tomaszdurka** [comment]
Tests are failing probably due to `fakefs` - not sure why as locally they pass.

I will also upgrade tests to not produce warnings.

**Comment by njam** [comment]
Looks good.

Error handling works good? If a thread fails, what happens?

**Comment by tomaszdurka** [comment]
Seems versioning in ruby gems is not as they say it should. Limiting version of fs to `0.5.2`

**Comment by tomaszdurka** [comment]
@njam
Regarding exceptions I've tested it extensively using Fork, but then thought Thread is much better for this situation. I've adjusted code that Threads now throw to "parent".

Please take a look at latest changes.

**Comment by njam** [comment]
lgtm, can we easily add a spec for that failing behaviour of start/stop?

**Comment by tomaszdurka** [comment]
Merging as discussed.

**Pull request merged**
